//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeceasedPlants
    {
        public int PlantId { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public string CauseOfDeath { get; set; }
        public System.DateTime DeathDate { get; set; }
        public int OwnerId { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
