//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraveyardPlantsDBEntities : DbContext
    {
        public GraveyardPlantsDBEntities()
            : base("name=GraveyardPlantsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BonusesFines> BonusesFines { get; set; }
        public DbSet<DeceasedPlants> DeceasedPlants { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<OrderItems> OrderItems { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<QualityChecks> QualityChecks { get; set; }
        public DbSet<RitualGoods> RitualGoods { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ServiceOrders> ServiceOrders { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Shifts> Shifts { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
