//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int GoodId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual RitualGoods RitualGoods { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
