//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.QualityChecks = new HashSet<QualityChecks>();
            this.ServiceOrders = new HashSet<ServiceOrders>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<QualityChecks> QualityChecks { get; set; }
        public virtual ICollection<ServiceOrders> ServiceOrders { get; set; }
    }
}
