//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RitualGoods
    {
        public RitualGoods()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int GoodId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
