//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public int ShiftId { get; set; }
        public int GardenerId { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Notes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
