//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenGarden.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.BonusesFines = new HashSet<BonusesFines>();
            this.DeceasedPlants = new HashSet<DeceasedPlants>();
            this.Logs = new HashSet<Logs>();
            this.Orders = new HashSet<Orders>();
            this.Shifts = new HashSet<Shifts>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public int RoleId { get; set; }
        public string AvatarPath { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<BonusesFines> BonusesFines { get; set; }
        public virtual ICollection<DeceasedPlants> DeceasedPlants { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}
